[package]
name = "tig"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@mail.com>"]

[dependencies]
error-chain = "*"
term = { path = "../term" }
common = { path = "../common" }
system = { path = "../system" }
unroll = { path = "../unroll" }

