language: rust

rust:
  - stable

sudo: false

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo build --release
  
os:
  - linux
  - osx
  
branchs:
  only:
    - master
