[package]
name = "kino"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
nom = "0.5.0"
term = { path = "term" }
event = { path = "event" }
unroll = { path = "unroll" }
system = { path = "system" }
kind = { path = "kind" }
bmc = { path = "bmc" }
