[package]
name = "kino"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
ansi_term = "0.7.0"
nom = "0.5.0"
rsmt2 = { git = "https://bitbucket.org/AdrienChampion/rsmt2.git" }
term = { path = "term" }
event = { path = "event" }
unroll = { path = "unroll" }
system = { path = "system" }
kind = { path = "kind" }
bmc = { path = "bmc" }