[package]
name = "kino"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
ansi_term = "0.7.0"
term = { path = "term" }
event = { path = "event" }
system = { path = "system" }
bmc = { path = "bmc" }