[package]
name = "term"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
num = "*"
regex = "*"
nom = { version = "*", features = [ "regexp" ] }
hashconsing = "*"