[package]
name = "term"
version = "0.2.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
error-chain = "*"
num = "*"
nom = "*"
rand = "*"
hashconsing = "*"
rsmt2 = { git = "https://github.com/kino-mc/rsmt2" }