[package]
name = "term"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
num = "*"
nom = "*"
rand = "*"
hashconsing = "*"
rsmt2 = { git = "https://github.com/kino-mc/rsmt2" }