[package]
name = "pruner"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
error-chain = "*"
term = { path = "../term" }
common = { path = "../common" }
system = { path = "../system" }
unroll = { path = "../unroll" }

