[package]
name = "conf"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@mail.com>"]

[dependencies]
common = { path = "../common" }
bmc = { path = "../bmc" }
kind = { path = "../kind" }
