[package]
name = "unroll"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@mail.com>"]

[dependencies]
error-chain = "*"
term = { path = "../term" }
system = { path = "../system" }
common = { path = "../common" }
