[package]
name = "bmc"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@mail.com>"]

[dependencies]
nom = "1.0.1"
term = { path = "../term" }
common = { path = "../common" }
system = { path = "../system" }
unroll = { path = "../unroll" }
