[package]
name = "bmc"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@mail.com>"]

[dependencies]
term = { path = "../term" }
event = { path = "../event" }
system = { path = "../system" }
